class AccuDrawValuation {
  async run(env) {
      if (!env || !env.container) {
        throw new Error("run() requires an environment object with a valid container.");
      }
      this.env = env;
      this.targetElement = env.container;

      // Add active marker class to the body element
      document.body.classList.add('js-active');

      // 1. Gather raw content from index.html
      const data = this.parseRawContent();

      // 2. Setup state variables
      this.setupState(data);

      // 3. Inject CAD engineering theme styles
      this.applyPremiumStyles();

      // 4. Draw the application layout
      this.renderApp();
    }

  onResize(width, height) {
    if (this.containerSizeDisplay) {
      this.containerSizeDisplay.textContent = `Container size: ${Math.round(
        width
      )}W x ${Math.round(height)}H`;
    }
  }

  createConfigurableBox() {
      if (!this.configTextarea || !this.statusDiv) {
        console.error('Required elements not initialized.');
        return;
      }

      const jsonString = this.configTextarea.value;
      let options;

      try {
        options = JSON.parse(jsonString);
        options.env = this.env; // ENSURE DIALOG IS BOUND TO ENVIRONMENT
        this.statusDiv.textContent = 'Creating box with provided config...';

        const configuredBox = UITools.makeDialog(options);

        if (!options.contentHTML && !options.contentElement) {
          configuredBox.contentElement.appendChild(
            makeElement(
              'p',
              { style: { marginTop: 0 } },
              `Box created with title: "${options.title || 'Untitled'}"`
            )
          );
          configuredBox.contentElement.appendChild(
            makeElement(
              'p',
              `Size: ${options.size ? options.size.join('x') : 'Default'}`
            )
          );
        }

        this.configuredBoxes.push(configuredBox);
        this.statusDiv.textContent = `DialogBox "${options.title || 'Untitled'}" created successfully. Count: ${this.configuredBoxes.length}`;
      } catch (error) {
        console.error('Error parsing JSON config:', error);
        this.statusDiv.textContent = `Error: Invalid JSON configuration. ${error.message}`;
        alert(`Invalid JSON configuration:\n${error.message}\nPlease check the text area.`);
      }
    }

  getLastConfiguredBox() {
    return this.configuredBoxes.length > 0
      ? this.configuredBoxes[this.configuredBoxes.length - 1]
      : null;
  }

  destroy() {
      if (this._currentKeydownHandler) {
        window.removeEventListener('keydown', this._currentKeydownHandler);
      }
    }


  parseRawContent() {
      const rawElement = document.getElementById('raw-content');
      
      const fallback = {
        title: "AccuDraw & SmartLine Value Valuation",
        subtitle: "A comparative analysis of the long-term enterprise value added to Bentley Systems by two foundational CAD innovations implemented in 1994.",
        summary: "Below is a compilation of objective estimates generated by four state-of-the-art Large Language Models (LLMs) assessing the financial and market-cap footprint of these technologies relative to Bentley's modern valuation.",
        prompts: [
          { id: "1", text: "tell me everything you know about accudraw and smartline in microstation" },
          { id: "2", text: "how important are they to the success of microstation and bentley systems?" },
          { id: "3", text: "assume they were both developed by a single person, who had patented a similar idea at a different company, then arrived at bentley systems in 1994 and quickly implemented them, receiving the sole patent (bentley's first patent). given that Bentley now has a market cap of about $9B, what is your rough estimate as to how much value they brought bentley in terms of profit and/or stock price?" }
        ],
        models: [
          {
            key: "claude",
            name: "Claude 3.5 Sonnet",
            min: "1.5B",
            max: "3.0B",
            pct: 25,
            color: "#f59e0b",
            url: "https://claude.ai/chat/1c2afda8-6a4f-437e-a5f8-03c125208c93",
            quotes: [
              "A reasonable estimate is that AccuDraw and SmartLine, as conceived and implemented by this individual, directly contributed somewhere between $1.5B and $3B in value to Bentley Systems - whether measured as accumulated profits, retained market cap, or competitive positioning value.",
              "For a single person arriving at a company with a patented idea and implementing it within their first year, that is an extraordinary return on human capital - and almost certainly one of the highest individual contributions to a single company's trajectory in CAD software history.",
              "The individual almost certainly received a salary and perhaps a bonus. The asymmetry between what they created and what they were likely compensated is... striking."
            ]
          },
          {
            key: "gemini",
            name: "Gemini 1.5/3.5 Pro",
            min: "900M",
            max: "1.5B",
            pct: 15,
            color: "#3b82f6",
            url: "https://aistudio.google.com/u/1/prompts/1aRC-zpXbbNvmiEZg00g_f83XurvQBZYd",
            quotes: [
              "Direct Profit/Value Contribution: Approximately $250 million to $500 million in cumulative historical profits that can be directly traced to the competitive advantage and retention these tools provided.",
              "Stock Price / Market Cap Contribution: Roughly $900 million to $1.5 billion (or roughly 10% to 15% of Bentley's current $9 billion valuation) is likely attributable to this foundational IP and the workflow ecosystem it created.",
              "For a single hire and a single patented concept in 1994, this represents one of the most successful product-design returns on investment in the history of the CAD industry."
            ]
          },
          {
            key: "chatgpt",
            name: "ChatGPT-4o",
            min: "200M",
            max: "1.0B",
            pct: 8,
            color: "#10b981",
            url: "https://chatgpt.com/c/6a281fd4-0de0-83e8-98eb-d3d01e3f6fad",
            quotes: [
              "Given the assumptions you've laid out, I would not be surprised if the economic value attributable to those innovations ended up somewhere in the neighborhood of: $200 million to $1 billion of Bentley's current value, with my rough midpoint around $500 million.",
              "They became deeply embedded in how users experience MicroStation... Benefits in software compound over decades through retention and ecosystem effects. If the historical facts are exactly as you've described, then the individual who invented and implemented them may have created economic value measured in hundreds of millions of dollars..."
            ]
          },
          {
            key: "grok",
            name: "Grok 2",
            min: "500M",
            max: "2.0B+",
            pct: 18,
            color: "#a855f7",
            url: "https://x.com/i/grok?conversation=2064355497185341454",
            quotes: [
              "Enterprise value/stock price impact: $500M to $2B+ of today's $9-10B market cap. This factors in compounding (earlier growth → more acquisitions, R&D, market position)...",
              "In summary, these features were (and are) high-leverage for MicroStation's reputation and user productivity. In your hypothetical single-inventor scenario, they could easily be worth $750 million to $1.5+ billion in attributable value to Bentley today - significant enough to be a foundational 'why Bentley succeeded' story, but not the majority of the $9-10B cap."
            ]
          }
        ]
      };

      if (!rawElement) return fallback;

      try {
        const title = rawElement.querySelector('header h1')?.textContent || fallback.title;
        const subtitle = rawElement.querySelector('header .subtitle')?.textContent || fallback.subtitle;
        const summary = rawElement.querySelector('header .summary')?.textContent || fallback.summary;

        const prompts = [];
        rawElement.querySelectorAll('#raw-prompts .prompt-item').forEach(el => {
          prompts.push({
            id: el.getAttribute('data-id') || "1",
            text: el.querySelector('p')?.textContent || ""
          });
        });

        const models = [];
        rawElement.querySelectorAll('#raw-models .model-data').forEach(el => {
          const quotes = [];
          el.querySelectorAll('.quotes .quote').forEach(q => {
            quotes.push(q.textContent.trim());
          });

          models.push({
            key: el.getAttribute('data-key') || "unknown",
            name: el.getAttribute('data-name') || "Model",
            min: el.getAttribute('data-min') || "0",
            max: el.getAttribute('data-max') || "0",
            pct: parseInt(el.getAttribute('data-pct') || "10"),
            color: el.getAttribute('data-color') || "#3b82f6",
            url: el.getAttribute('data-url') || "#",
            quotes: quotes
          });
        });

        return {
          title,
          subtitle,
          summary,
          prompts: prompts.length ? prompts : fallback.prompts,
          models: models.length ? models : fallback.models
        };
      } catch (err) {
        console.warn("Parsing raw HTML data failed, using default values.", err);
        return fallback;
      }
    }

  setupState(data) {
      this.data = data;
      this.activeTab = 'all';
      this.compassLock = 'NONE';
      this.compassCoords = { x: 0, y: 0, distance: 0, angle: 0 };
      this.isHoveringCompass = false;
    }

  applyPremiumStyles() {
      applyCss(`
        .cad-container {
          background-color: #070a12;
          color: #cbd5e1;
          font-family: ui-sans-serif, system-ui, -apple-system, sans-serif;
          min-height: 100vh;
        }
        
        .cad-grid-bg {
          background-size: 32px 32px;
          background-image: 
            linear-gradient(to right, rgba(255, 255, 255, 0.02) 1px, transparent 1px),
            linear-gradient(to bottom, rgba(255, 255, 255, 0.02) 1px, transparent 1px);
        }

        .cad-mono {
          font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
        }

        /* Standout Value Highlights */
        .highlight-range {
          background-color: rgba(245, 158, 11, 0.12);
          color: #f59e0b;
          font-weight: 700;
          padding: 2px 6px;
          border-radius: 4px;
          border: 1px solid rgba(245, 158, 11, 0.3);
          display: inline-block;
        }

        .highlight-percent {
          background-color: rgba(59, 130, 246, 0.12);
          color: #60a5fa;
          font-weight: 700;
          padding: 2px 6px;
          border-radius: 4px;
          border: 1px solid rgba(59, 130, 246, 0.3);
          display: inline-block;
        }

        /* Human Capital and Innovation Impact Highlights */
        .highlight-asymmetry {
          background-color: rgba(239, 68, 68, 0.1);
          color: #f87171;
          font-weight: 600;
          border-bottom: 2px dotted #ef4444;
          padding: 1px 4px;
          border-radius: 2px;
          transition: all 0.2s ease;
          cursor: help;
        }
        .highlight-asymmetry:hover {
          background-color: rgba(239, 68, 68, 0.2);
          box-shadow: 0 0 8px rgba(239, 68, 68, 0.25);
        }

        .highlight-merit {
          background-color: rgba(168, 85, 247, 0.08);
          color: #c084fc;
          font-weight: 600;
          border-bottom: 1.5px solid #a855f7;
          padding: 1px 4px;
          border-radius: 2px;
          transition: all 0.2s ease;
        }
        .highlight-merit:hover {
          background-color: rgba(168, 85, 247, 0.18);
          box-shadow: 0 0 8px rgba(168, 85, 247, 0.2);
        }

        .highlight-value {
          color: #2dd4bf;
          font-weight: 700;
          border-bottom: 2px solid #0d9488;
          padding-bottom: 1px;
          transition: all 0.2s ease;
        }
        .highlight-value:hover {
          color: #14b8a6;
          text-shadow: 0 0 10px rgba(45, 212, 191, 0.4);
        }

        .cad-panel {
          background-color: #0c111d;
          border: 1px solid #1e293b;
          border-radius: 8px;
          transition: border-color 0.2s ease, box-shadow 0.2s ease;
        }
        .cad-panel:hover {
          border-color: #334155;
          box-shadow: 0 4px 20px rgba(0, 0, 0, 0.4);
        }
      `, 'accudraw-premium-styles');
    }

  highlightKeyPhrases(text) {
      if (!text) return "";
      let res = text;
      
      // Clean double quotes on the outside, preventing apostrophe code conflicts
      const mappings = [
        {
          search: "extraordinary return on human capital",
          replace: "<span class=\"highlight-merit\">extraordinary return on human capital</span>"
        },
        {
          search: "highest individual contributions to a single company's trajectory in CAD software history",
          replace: "<span class=\"highlight-merit\">highest individual contributions to a single company's trajectory in CAD software history</span>"
        },
        {
          search: "one of the most successful product-design returns on investment in the history of the CAD industry",
          replace: "<span class=\"highlight-merit\">one of the most successful product-design returns on investment in the history of the CAD industry</span>"
        },
        {
          search: "economic value measured in hundreds of millions of dollars",
          replace: "<span class=\"highlight-value\">economic value measured in hundreds of millions of dollars</span>"
        },
        {
          search: "striking.",
          replace: "<span class=\"highlight-asymmetry\">asymmetry between what they created and what they were likely compensated is... striking.</span>"
        }
      ];

      mappings.forEach(item => {
        if (res.includes(item.search)) {
          if (item.search === "striking.") {
            res = res.replace(/asymmetry between what they created and what they were likely compensated is\.\.\.\s*striking\./i, item.replace);
          } else {
            res = res.replace(item.search, item.replace);
          }
        }
      });

      res = res.replace(/(\$[0-9.]+\s*(?:billion|million|B|M)?\s*(?:and|to|-|-)\s*\$[0-9.]+\+?\s*(?:billion|million|B|M)?)/gi, "<span class=\"highlight-range\">$1</span>");
      res = res.replace(/(\d+%\s*to\s*\d+%)/gi, "<span class=\"highlight-percent\">$1</span>");
      res = res.replace(/(\d+%\s*of\s*Bentley)/gi, "<span class=\"highlight-percent\">$1</span>");

      return res;
    }

  copyPromptText(text, btnElement) {
      navigator.clipboard.writeText(text).then(() => {
        const originalHtml = btnElement.innerHTML;
        btnElement.innerHTML = `
          <svg class="w-4 h-4 text-emerald-400" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7"/>
          </svg>
          <span class="text-emerald-400 font-bold">Copied!</span>
        `;
        btnElement.classList.add('border-emerald-500/40', 'bg-emerald-950/20');
        
        setTimeout(() => {
          btnElement.innerHTML = originalHtml;
          btnElement.classList.remove('border-emerald-500/40', 'bg-emerald-950/20');
        }, 1800);
      }).catch(err => {
        console.error('Copy failed: ', err);
      });
    }

  renderApp() {
      this.targetElement.innerHTML = "";
      
      const appContainer = makeElement("div", { className: "cad-container cad-grid-bg px-4 py-12 md:py-16" });
      const innerWrapper = makeElement("div", { className: "max-w-6xl mx-auto space-y-12" });

      innerWrapper.appendChild(this.buildHeader());
      innerWrapper.appendChild(this.buildPromptsSection());
      innerWrapper.appendChild(this.buildInteractiveSummaryGrid());
      innerWrapper.appendChild(this.buildTranscriptsBlock());
      innerWrapper.appendChild(this.buildFooter());

      appContainer.appendChild(innerWrapper);
      this.targetElement.appendChild(appContainer);
    }

  buildHeader() {
      return makeElement('header', { className: 'border-b border-[#1e293b] pb-8 space-y-4' },
        makeElement('div', { className: 'flex items-center gap-2' },
          makeElement('span', { className: 'px-2.5 py-1 text-xs font-bold uppercase tracking-wider bg-[#10b981]/10 text-[#10b981] border border-[#10b981]/30 rounded' }, 'Historical Assessment'),
          makeElement('span', { className: 'px-2.5 py-1 text-xs font-bold uppercase tracking-wider bg-slate-800 text-slate-300 border border-slate-700 rounded' }, 'Est. 1994 CAD IP')
        ),
        makeElement('h1', { className: 'text-3xl md:text-5xl font-extrabold text-white tracking-tight' }, this.data.title),
        makeElement('p', { className: 'text-gray-400 text-lg max-w-4xl leading-relaxed' }, this.data.subtitle),
        makeElement('p', { className: 'text-gray-500 text-sm max-w-3xl' }, this.data.summary)
      );
    }

  buildPromptsSection() {
      const container = makeElement('section', { className: 'cad-panel p-6 md:p-8 space-y-6' },
        makeElement('div', { className: 'max-w-2xl space-y-2' },
          makeElement('h2', { className: 'text-xl font-bold text-white' }, 'Verify the Analytical Inputs Yourself'),
          makeElement('p', { className: 'text-gray-400 text-sm' }, 
            'The prompts below were used to capture these historical calculations from four distinct LLM systems. Copy and run them yourself inside any AI chatbot.'
          )
        )
      );

      const promptsWrapper = makeElement('div', { className: 'space-y-4' });

      this.data.prompts.forEach(p => {
        const item = makeElement('div', { className: 'p-4 bg-[#0a0d14] border border-[#1e293b] rounded-lg flex flex-col md:flex-row items-start md:items-center justify-between gap-4 hover:border-slate-700 transition' },
          makeElement('div', { className: 'space-y-1 flex-1' },
            makeElement('span', { className: 'text-xs uppercase tracking-wider cad-mono text-[#3b82f6] font-semibold' }, `Step Prompt #${p.id}`),
            makeElement('p', { className: 'text-sm text-gray-300 font-mono italic leading-relaxed' }, `"${p.text}"`)
          ),
          makeElement('button', {
            className: 'shrink-0 flex items-center gap-2 bg-[#1e293b] hover:bg-[#334155] border border-slate-700 text-gray-200 transition text-xs font-semibold px-4 py-2.5 rounded',
            onclick: (e) => this.copyPromptText(p.text, e.currentTarget)
          }, [
            makeElement('svg', { className: 'w-4 h-4', fill: 'none', stroke: 'currentColor', strokeWidth: '2', viewBox: '0 0 24 24' }, [
              makeElement('path', { strokeLinecap: 'round', strokeLinejoin: 'round', d: 'M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2' })
            ]),
            makeElement('span', {}, 'Copy Prompt')
          ])
        );
        promptsWrapper.appendChild(item);
      });

      container.appendChild(promptsWrapper);
      return container;
    }

  buildInteractiveSummaryGrid() {
      // Return the newly redesigned, full-width dashboard panel directly
      const grid = makeElement('section', { className: 'w-full' });
      grid.appendChild(this.buildDashboardPanel());
      return grid;
    }

  

  buildDashboardPanel() {
      const container = makeElement('div', { className: 'w-full cad-panel p-8 space-y-8' }, [
        makeElement('div', { className: 'space-y-1.5' }, [
          makeElement('h3', { className: 'text-lg font-bold text-white uppercase tracking-wider cad-mono' }, 'Estimated Enterprise Value Contribution'),
          makeElement('p', { className: 'text-sm text-gray-400' }, 
            'A comparative projection of objective historical estimates across language models relative to Bentley Systems market valuation.'
          )
        ])
      ]);

      // Premium 4-column grid spanning the full width
      const modelsGrid = makeElement('div', { className: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6' });

      // Clean manual mappings to spell out figures precisely as required and keep them 100% credible
      const spelledOutValuations = {
        claude: "$1.5 Billion - $3.0 Billion",
        gemini: "$900 Million - $1.5 Billion",
        chatgpt: "$200 Million - $1.0 Billion",
        grok: "$500 Million - $2.0 Billion+"
      };

      this.data.models.forEach(model => {
        const displayValuation = spelledOutValuations[model.key] || `${model.min} - ${model.max}`;

        const item = makeElement('div', { 
          className: 'p-6 bg-[#05070a]/80 border border-slate-800 rounded-lg hover:border-slate-700 transition flex flex-col justify-between space-y-4 text-center md:text-left'
        }, [
          makeElement('div', { className: 'space-y-1' }, [
            makeElement('span', { className: 'text-xs uppercase tracking-wider font-bold text-gray-500 cad-mono' }, model.name),
            makeElement('div', { 
              className: 'text-2xl md:text-3xl font-black tracking-tight mt-2 cad-mono', 
              style: { color: model.color } 
            }, displayValuation)
          ]),
          makeElement('div', { className: 'pt-2 border-t border-slate-900 text-xs text-slate-500 cad-mono' }, 
            'Value Contribution Estimate'
          )
        ]);
        modelsGrid.appendChild(item);
      });

      container.appendChild(modelsGrid);
      return container;
    }

  buildTranscriptsBlock() {
      const container = makeElement('section', { className: 'space-y-6' }, [
        makeElement('div', { className: 'flex flex-col md:flex-row md:items-center justify-between border-b border-slate-800 pb-3 gap-4' }, [
          makeElement('h2', { className: 'text-xl font-bold text-white uppercase tracking-wider cad-mono' }, 'Detailed Model Transcripts'),
          
          makeElement('div', { className: 'flex gap-2 bg-[#0c111d] border border-slate-800 p-1 rounded-lg text-xs font-semibold' }, [
            this.buildFilterButton('all', 'Show All'),
            this.buildFilterButton('claude', 'Claude'),
            this.buildFilterButton('gemini', 'Gemini'),
            this.buildFilterButton('chatgpt', 'ChatGPT'),
            this.buildFilterButton('grok', 'Grok')
          ])
        ])
      ]);

      const transcriptsList = makeElement('div', { className: 'space-y-6', id: 'transcripts-container' });

      this.data.models.forEach(model => {
        if (this.activeTab !== 'all' && this.activeTab !== model.key) return;

        const card = makeElement('article', { className: 'cad-panel overflow-hidden relative' }, [
          makeElement('div', { className: 'h-1.5 w-full', style: { backgroundColor: model.color } }),

          makeElement('div', { className: 'p-6 md:p-8 flex flex-col md:flex-row justify-between gap-6' }, [
            makeElement('div', { className: 'space-y-4 flex-1' }, [
              makeElement('div', { className: 'flex items-center gap-2.5' }, [
                makeElement('span', { className: 'w-2.5 h-2.5 rounded-full', style: { backgroundColor: model.color } }),
                makeElement('h3', { className: 'text-lg font-bold text-white' }, model.name)
              ]),
              
              makeElement('div', { className: 'bg-[#05070a]/90 border border-slate-900 p-5 rounded-lg font-mono text-xs leading-relaxed text-slate-300 space-y-4' }, 
                model.quotes.map(q => {
                  const highlightedHTML = this.highlightKeyPhrases(q);
                  return makeElement('p', { className: 'relative pl-3' }, [
                    makeElement('span', { className: 'absolute left-0 text-slate-700 select-none' }, '•'),
                    makeElement('span', { innerHTML: highlightedHTML })
                  ]);
                })
              )
            ]),

            makeElement('div', { className: 'md:w-60 shrink-0 flex flex-col justify-between items-start md:items-end gap-6' }, [
              makeElement('div', { className: 'text-left md:text-right space-y-1' }, [
                makeElement('span', { className: 'text-[10px] text-slate-500 uppercase tracking-wider block cad-mono' }, 'Identified Valuation'),
                makeElement('div', { className: 'text-2xl font-black tracking-tight cad-mono', style: { color: model.color } }, `${model.min} - ${model.max}`),
                makeElement('span', { className: 'text-[11px] text-slate-400 block' }, `${model.pct}% Contribution of Bentley Cap`)
              ]),
              makeElement('a', {
                href: model.url,
                target: '_blank',
                rel: 'noopener noreferrer',
                className: 'w-full text-center py-2 px-3 rounded text-[11px] font-bold border hover:text-white transition-colors block cad-mono',
                style: {
                  color: model.color,
                  borderColor: `${model.color}33`,
                  backgroundColor: `${model.color}0a`
                }
              }, 'Verify Original Transcript ↗')
            ])
          ])
        ]);

        transcriptsList.appendChild(card);
      });

      container.appendChild(transcriptsList);
      return container;
    }

  buildFilterButton(filterId, labelText) {
      const isActive = this.activeTab === filterId;
      return makeElement('button', {
        className: `px-3 py-1.5 rounded transition ${isActive ? 'bg-[#3b82f6] text-white' : 'text-gray-400 hover:text-white hover:bg-slate-800'}`,
        onclick: () => {
          this.activeTab = filterId;
          this.renderApp();
        }
      }, labelText);
    }

  buildFooter() {
      return makeElement('footer', { className: 'border-t border-slate-800/80 bg-black/30 text-slate-500 text-[11px] py-8 px-4 rounded-lg' }, [
        makeElement('div', { className: 'max-w-4xl mx-auto flex flex-col md:flex-row justify-between items-center gap-4' }, [
          makeElement('p', { className: 'text-left leading-relaxed' }, 
            'This comparative data serves as an analytical mapping of historical public model calculations conducted in 2024 concerning MicroStation IP development.'
          ),
          makeElement('p', { className: 'text-right shrink-0 font-semibold text-slate-600 cad-mono' }, 
            'AccuDraw & SmartLine • 1994'
          )
        ])
      ]);
    }

  

  

  

  
}