// phase2-managed-migration: internal imports/exports stripped
class ProjectAnalysisManager {
  
  constructor(app) {
    this.app = app;
    this.importMap = new Map(); // Key: filePath, Value: Array of imported symbols/paths
    this.referenceMap = new Map(); // Key: symbolName, Value: Set of filePaths where it's referenced
  }

  async buildImportMap() {    const vfs = await this._analysisGetVfs();    const files = await this._analysisListReadableFiles(vfs);    const importMap = new Map();    for (const filePath of files) {      if (!this._analysisShouldScanSourceFile(filePath)) {        continue;      }      const content = await this._analysisReadFile(vfs, filePath);      if (typeof content !== "string") {        continue;      }      const imports = this._analysisExtractImports(filePath, content);      if (imports.length) {        importMap.set(filePath, imports);      }    }    this.importMap = importMap;    return importMap;  }

  getImportMap() {    return this.importMap || new Map();  }

  async buildReferenceMap(symbolMap) {    const vfs = await this._analysisGetVfs();    const files = await this._analysisListReadableFiles(vfs);    const symbols = this._analysisNormalizeSymbols(symbolMap);    const referenceMap = new Map();    for (const symbol of symbols) {      referenceMap.set(symbol, []);    }    for (const filePath of files) {      if (!this._analysisShouldScanSourceFile(filePath)) {        continue;      }      const content = await this._analysisReadFile(vfs, filePath);      if (typeof content !== "string") {        continue;      }      for (const symbol of symbols) {        if (!symbol || symbol.length < 2) {          continue;        }        if (content.includes(symbol)) {          referenceMap.get(symbol).push(filePath);        }      }    }    this.referenceMap = referenceMap;    return referenceMap;  }

  getReferenceMap() {    return this.referenceMap || new Map();  }

  getFilesForConcept(conceptName) {    const query = typeof conceptName === "string"      ? conceptName.trim().toLowerCase()      : "";    if (!query) {      return [];    }    const matches = new Set();    const referenceMap = this.getReferenceMap();    for (const entry of referenceMap.entries()) {      const symbol = String(entry[0]);      const symbolNeedles = this._analysisConceptNeedles(symbol);      if (this._analysisConceptMatches(query, symbol, symbolNeedles)) {        for (const filePath of entry[1]) {          matches.add(filePath);        }        continue;      }      for (const filePath of entry[1]) {        if (this._analysisConceptMatches(query, filePath, this._analysisConceptNeedles(filePath))) {          matches.add(filePath);        }      }    }    const importMap = this.getImportMap();    for (const entry of importMap.entries()) {      const filePath = entry[0];      const imports = entry[1];      if (this._analysisConceptMatches(query, filePath, this._analysisConceptNeedles(filePath))) {        matches.add(filePath);        continue;      }      for (const importInfo of imports) {        const haystack = [          importInfo.raw,          importInfo.specifier,          importInfo.kind,          importInfo.filePath        ].join(" ");        if (this._analysisConceptMatches(query, haystack, this._analysisConceptNeedles(haystack))) {          matches.add(filePath);        }      }    }    return Array.from(matches).sort();  }

    

  async _analysisGetVfs() {    if (!this.app) {      return null;    }    if (typeof this.app.refreshVirtualFileSystemStores === "function") {      return await this.app.refreshVirtualFileSystemStores();    }    return this.app.vfs || null;  }

  async _analysisListReadableFiles(vfs) {    if (vfs && typeof vfs.listFiles === "function") {      try {        const files = await vfs.listFiles({          includeStatic: false        });        if (Array.isArray(files)) {          return files;        }      } catch (error) {        this._analysisLogFallback("listFiles", "", error);      }    }    if (this.app?.commands && typeof this.app.commands.getRawFileList === "function") {      try {        const files = await this.app.commands.getRawFileList({});        if (Array.isArray(files)) {          return files;        }      } catch (error) {        this._analysisLogFallback("commands.getRawFileList", "", error);      }    }    if (this.app?.projectFilesManager && typeof this.app.projectFilesManager.collectPromptFilesAcrossOpenTrees === "function") {      try {        const files = await this.app.projectFilesManager.collectPromptFilesAcrossOpenTrees();        if (Array.isArray(files)) {          return files            .map(item => typeof item === "string" ? item : item && item.path)            .filter(Boolean);        }      } catch (error) {        this._analysisLogFallback("collectPromptFilesAcrossOpenTrees", "", error);      }    }    return [];  }

  async _analysisReadFile(vfs, filePath) {    if (vfs && typeof vfs.readFile === "function") {      try {        const content = await vfs.readFile(filePath, {          nullOnMissing: true        });        if (typeof content === "string") {          return content;        }      } catch (error) {        this._analysisLogFallback("vfs.readFile", filePath, error);      }    }    if (this.app?.commands && typeof this.app.commands.fetchFileContentForApp === "function") {      try {        const content = await this.app.commands.fetchFileContentForApp(filePath);        if (typeof content === "string") {          return content;        }      } catch (error) {        this._analysisLogFallback("commands.fetchFileContentForApp", filePath, error);      }    }    if (this.app?.projectFilesManager && typeof this.app.projectFilesManager.getFileContent === "function") {      try {        const content = await this.app.projectFilesManager.getFileContent(filePath);        if (typeof content === "string") {          return content;        }      } catch (error) {        this._analysisLogFallback("projectFilesManager.getFileContent", filePath, error);      }    }    return null;  }

  _analysisShouldScanSourceFile(filePath) {    if (typeof filePath !== "string") {      return false;    }    if (filePath.includes("/.vibes-history/")) {      return false;    }    const lower = filePath.toLowerCase();    return lower.endsWith(".js") ||      lower.endsWith(".mjs") ||      lower.endsWith(".cjs") ||      lower.endsWith(".html") ||      lower.endsWith(".css") ||      lower.endsWith(".md") ||      lower.endsWith(".json");  }

  _analysisExtractImports(filePath, content) {    const imports = [];    const lines = content.split("\n");    for (let index = 0; index < lines.length; index++) {      const raw = lines[index].trim();      if (!raw) {        continue;      }      if (raw.startsWith("import ") || raw.startsWith("export ")) {        const specifier = this._analysisExtractStaticModuleSpecifier(raw);        if (specifier) {          imports.push({            filePath,            line: index + 1,            kind: raw.startsWith("export ") ? "export-from" : "static-import",            specifier,            raw          });        }        continue;      }      if (raw.includes("import(")) {        const specifier = this._analysisExtractDynamicModuleSpecifier(raw);        if (specifier) {          imports.push({            filePath,            line: index + 1,            kind: "dynamic-import",            specifier,            raw          });        }      }    }    return imports;  }

  _analysisExtractStaticModuleSpecifier(line) {    const fromIndex = line.lastIndexOf(" from ");    if (fromIndex < 0) {      return "";    }    const tail = line.slice(fromIndex + " from ".length).trim();    return this._analysisExtractFirstQuotedString(tail);  }

  _analysisExtractDynamicModuleSpecifier(line) {    const importIndex = line.indexOf("import(");    if (importIndex < 0) {      return "";    }    const tail = line.slice(importIndex + "import(".length).trim();    return this._analysisExtractFirstQuotedString(tail);  }

  _analysisExtractFirstQuotedString(text) {    if (typeof text !== "string") {      return "";    }    const single = text.indexOf("'");    const double = text.indexOf('"');    let quote = "";    let start = -1;    if (single >= 0 && double >= 0) {      if (single < double) {        quote = "'";        start = single;      } else {        quote = '"';        start = double;      }    } else if (single >= 0) {      quote = "'";      start = single;    } else if (double >= 0) {      quote = '"';      start = double;    }    if (start < 0) {      return "";    }    const end = text.indexOf(quote, start + 1);    if (end < 0) {      return "";    }    return text.slice(start + 1, end);  }

  _analysisNormalizeSymbols(symbolMap) {    const symbols = new Set();    if (symbolMap instanceof Map) {      for (const key of symbolMap.keys()) {        if (typeof key === "string") {          symbols.add(key);        }      }    } else if (symbolMap && typeof symbolMap === "object") {      for (const key of Object.keys(symbolMap)) {        symbols.add(key);      }    }    if (this.app?.symbolMap instanceof Map) {      for (const key of this.app.symbolMap.keys()) {        if (typeof key === "string") {          symbols.add(key);        }      }    }    if (!symbols.size) {      const importMap = this.getImportMap();      for (const filePath of importMap.keys()) {        const base = this._analysisFileBaseName(filePath);        if (base) {          symbols.add(base);        }      }    }    return Array.from(symbols).sort();  }

  _analysisFileBaseName(filePath) {    if (typeof filePath !== "string") {      return "";    }    const parts = filePath.split("/");    const filename = parts[parts.length - 1] || "";    const dot = filename.lastIndexOf(".");    if (dot <= 0) {      return filename;    }    return filename.slice(0, dot);  }

  _analysisLogFallback(operation, filePath, error) {    const message = error && error.message ? error.message : String(error);    if (this.app && typeof this.app.logFileOp === "function") {      this.app.logFileOp("debug", "ProjectAnalysisManager VFS fallback", {        operation,        path: filePath,        error: message      });      return;    }    if (this.app?.fileLogger && typeof this.app.fileLogger.log === "function") {      this.app.fileLogger.log("debug", "ProjectAnalysisManager VFS fallback", {        operation,        path: filePath,        error: message      });    }  }

  _analysisConceptMatches(query, text, needles = []) {    const haystack = String(text || "").toLowerCase();    if (!query || !haystack) {      return false;    }    if (haystack.includes(query)) {      return true;    }    for (const needle of needles) {      if (needle && needle.includes(query)) {        return true;      }      if (needle && query.includes(needle) && needle.length >= 3) {        return true;      }    }    return false;  }

  _analysisConceptNeedles(text) {    const source = String(text || "");    const words = this._analysisConceptWords(source);    const acronym = words      .filter(word => word.length > 0)      .map(word => word[0])      .join("")      .toLowerCase();    const compact = words.join("").toLowerCase();    const fileBase = this._analysisFileBaseName(source);    const fileWords = this._analysisConceptWords(fileBase);    const fileAcronym = fileWords      .filter(word => word.length > 0)      .map(word => word[0])      .join("")      .toLowerCase();    return Array.from(new Set([      source.toLowerCase(),      compact,      acronym,      fileBase.toLowerCase(),      fileWords.join("").toLowerCase(),      fileAcronym    ].filter(Boolean)));  }

  _analysisConceptWords(text) {    const source = String(text || "")      .replaceAll("/", " ")      .replaceAll("\\", " ")      .replaceAll("-", " ")      .replaceAll("_", " ")      .replaceAll(".", " ");    const camelBoundaryPattern = new RegExp("([a-z0-9])([A-Z])", "g");    const whitespacePattern = new RegExp("\\s+");    const spaced = source.replace(camelBoundaryPattern, "$1 $2");    return spaced      .split(whitespacePattern)      .map(word => word.trim().toLowerCase())      .filter(Boolean);  }


  static _doc() {
      return [
        this._doc_overview()
      ].join('\n\n');
    }

  static _doc_overview() {
      return "### ProjectAnalysisManager\n\nAnalyzes project source files to construct import maps and track symbol references. Powers advanced features such as cross-file concept navigation and dead-code detection.";
    }
}

