var NeuralPath = {
// these were generated by "drawing" with the neuronEvent2
// function
setDefs : {
innerAreaBulb : [
  [
    [0,0],
    [-1,-1],
    [1,0],
    [-1,-1],
    [1,0],
    [1,0],
    [0,1],
    [0,1],
    [-1,1],
    [0,1],
    [-1,-1],
    [0,-1],
    [-1,-1]
  ],
  [
    [1,0],
    [-2,0],
    [0,-1],
    [1,0],
    [1,0],
    [1,0],
    [-3,-1],
    [1,0],
    [1,0],
    [0,3],
    [-1,0],
    [0,1]
  ]
],
outerRingBulb : [
  [
    [2,0],
    [0,-1],
    [0,-1],
    [-1,-1],
    [-1,0],
    [-1,0],
    [-1,0],
    [0,1],
    [-1,1],
    [1,1],
    [0,1],
    [1,1],
    [0,1],
    [1,0],
    [1,-1],
    [0,-1]
  ],
  [
    [2,0],
    [1,-1],
    [-1,-1],
    [0,-1],
    [-1,0],
    [-1,0],
    [-1,0],
    [-1,1],
    [0,1],
    [0,1],
    [1,1],
    [0,1],
    [1,1],
    [1,0],
    [0,-1],
    [1,-1]    
  ]
],
innerAreaButton : [
  [
    [0,0],
    [1,0],
    [-1,-1],
    [-1,0],
    [0,1],
    [0,1],
    [1,0]  
  ],
  [
    [0,0],
    [1,0],
    [0,-1],
    [-1,0],
    [-1,1],
    [1,1],
    [1,0]
  ]
],
outerRingButton : [
  [
    [2,0],
    [-1,-1],
    [0,-1],
    [-1,0],
    [-1,0],
    [-1,1],
    [0,1],
    [0,1],
    [1,1],
    [1,0],
    [1,0],
    [0,-1]
  ],
  [
    [2,0],
    [0,-1],
    [-1,-1],
    [-1,0],
    [-1,0],
    [0,1],
    [-1,1],
    [1,1],
    [0,1],
    [1,0],
    [1,0],
    [1,-1]    
  ]
],
smallRing : [
  [
	[0,-1],
	[1,1],
	[-1,1],
	[-1,0],
	[0,-1],
	[0,-1]
	],
	[
	[1,-1],
	[0,1],
	[0,1],
	[-1,0],
	[-1,-1],
	[1,-1]
	]
]
},

//-------------------------------------------------
getPathConstant : function (startX, startY, type) {
  var set = [];
  
  // use first set if Y is even, second if odd
  var def = this.setDefs[type][startY%2];
  var x = startX, y = startY;
  for (var i=0; i < def.length; i++) {
    x += def[i][0];
    y += def[i][1];
  
    if (this.allowWrap) {
      if (x >= Brain.xLimit)
          x = x - Brain.xLimit;
      else if (x < 0)
          x = Brain.xLimit + x;
      if (y >= Brain.yLimit)
          y = y - Brain.yLimit;
      else if (y < 0)
          y = Brain.yLimit + y;
      set.push ({neuron: Brain.grid[x][y], x: x, y: y});
      }
    else {
      if (x < Brain.xLimit && x >= 0 && y < Brain.yLimit && y >= 0)
        set.push ({neuron: Brain.grid[x][y], x: x, y: y});
      else
        set.push ({neuron: null, x: x, y: y});
        }
    }
  return set;
  }
};
